categories:
  - title: '🚀 Features'
    labels: 
      - 'feat'
      - 'feature'
  - title: '🐛 Fixes'
    labels:
      - 'fix'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '🧰 Maintenance'
    labels: 
      - 'build'
      - 'doc'
      - 'docs'
      - 'chore'
      - 'refactor'
      - 'style'