version: "3.9"
services:
  image1:
    build:
      context: .
      dockerfile: docker/image1/Dockerfile
    image: ${IMAGE_1_REPOSITORY:-image1}:${IMAGE_TAG:-local}
    security_opt:
      - label:disable
  image2:
    build:
      context: .
      dockerfile: docker/image2/Dockerfile
    image: ${IMAGE_2_REPOSITORY:-image2}:${IMAGE_TAG:-local}