name: Deploy to Sandbox

on:
  workflow_run:
    workflows: [On push to main]
    types:
      - completed

concurrency: Deploy to Sandbox

jobs:
  Deploy:
    uses: ./.github/workflows/aws_deploy.yml
