on:
  workflow_call:
    inputs:
      image_tag:
        description: Build app type
        required: true
        type: string

env:
  IMAGE_1_REPOSITORY: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/image1
  IMAGE_2_REPOSITORY: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/image2


jobs:
  Builder:
    concurrency: Builder
    runs-on: ubuntu-latest
    steps:
      - id: user
        run: |
          echo name=$(whoami) >> $GITHUB_OUTPUT
          echo gid=$(id -g) >> $GITHUB_OUTPUT
          echo uid=$(id -u) >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push images to GitHub Container Registry
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-compose.yml
          load: true
          set: |
            *.platform=linux/amd64
            image1.args.APP_TYPE=${{ inputs.image_tag }}
            image1.args.USER=${{ steps.user.outputs.name }}
            image1.args.USER_GID=${{ steps.user.outputs.gid }}
            image1.args.USER_UID=${{ steps.user.outputs.uid }}
            image1.cache-from=ref=${{ env.IMAGE_1_REPOSITORY }}:builder-cache,type=registry
            image1.cache-from=ref=${{ env.IMAGE_1_REPOSITORY }}:${{ inputs.image_tag }}-cache,type=registry
            image1.cache-to=mode=max,ref=${{ env.IMAGE_1_REPOSITORY }}:builder-cache,type=registry
            image1.cache-to=mode=max,ref=${{ env.IMAGE_1_REPOSITORY }}:${{ inputs.image_tag }}-cache,type=registry
            image1.pull=true
            image1.tags=${{ env.IMAGE_1_REPOSITORY }}:${{ inputs.image_tag }}
            image2.cache-from=ref=${{ env.IMAGE_2_REPOSITORY }}:builder-cache,type=registry
            image2.cache-from=ref=${{ env.IMAGE_2_REPOSITORY }}:${{ inputs.image_tag }}-cache,type=registry
            image2.cache-to=mode=max,ref=${{ env.IMAGE_2_REPOSITORY }}:builder-cache,type=registry
            image2.cache-to=mode=max,ref=${{ env.IMAGE_2_REPOSITORY }}:${{ inputs.image_tag }}-cache,type=registry
            image2.pull=true
            image2.tags=${{ env.IMAGE_2_REPOSITORY }}:${{ inputs.image_tag }}
          targets: image1,image2
      - run: |
          docker images
