name: Run Tests
on: 
  push:
    branches:
      - main

    
jobs:
  Test:
    if: ${{ github.actor != 'dependabot[bot]'}}
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "test"
