on: 
  push:
    branches:
      - main

jobs:
  Test:
    uses: ./.github/workflows/gha.yml
    with:
      image_tag: "test"
  Publish:
    uses: ./.github/workflows/gha.yml
    with:
      image_tag: "publish"
