name: On push to main
on: 
  push:
    branches:
      - main

    
jobs:
  Test:
    if: ${{ github.actor == 'dependabot[bot]'}}
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "test"
  Build:
    needs: Test
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "release"

