on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Test:
    uses: ./.github/workflows/gha.yml
    with:
      image_tag: "test"
  Publish:
    needs: Test
    uses: ./.github/workflows/gha.yml
    with:
      image_tag: "publish"
