name: On main
on: 
  push:
    branches:
      - main

jobs:
  Test:
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "test"
  Build:
    needs: Test
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "release"
  Draft:
    needs: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}