name: On push to main
on: 
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Test:
    if: ${{ github.actor == 'dependabot[bot]'}}
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "test"
  Build:
    needs: Test
    uses: ./.github/workflows/app_run.yml
    with:
      image_tag: "release"
  Draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}