on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: write

jobs:
  Deploy:
    name: Deploy to sandbox environment
    uses: ./.github/workflows/aws_deployment.yml
