name: GHCR Maintenance Actions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  Prune:
    strategy:
      matrix:
        name: [image1, image2]
    name: Prune images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Gather variables
        id: gather-vars
        run: |
          echo container=$(echo '${{ github.repository }}' | cut -f2 -d '/')/${{ matrix.name }} >> $GITHUB_OUTPUT

      - name: Prune tagged images from GHCR
        continue-on-error: true
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          container: ${{ steps.gather-vars.outputs.container }}
          dry-run: false
          organization: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-regex: ^${{ github.ref }}-.*$

