name: Create release draft

on:
  workflow_run:
    workflows: [On push to main]
    types:
      - completed

concurrency: Create release draft

permissions:
  contents: read

jobs:
  Draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}